version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ponesaltitante_db
    restart: always
    environment:
      POSTGRES_USER: hobbit
      POSTGRES_PASSWORD: condado123
      POSTGRES_DB: ponesaltitante
    ports:
      - "5432:5432"
    # Monta o arquivo init.sql para criar o banco do zero
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      # Volume temporário para não persistir dados entre reinícios
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
    # Declaração para que o volume seja anônimo e recriado do zero
    # Para desenvolvimento, você pode limpar sempre com `docker-compose down -v`
